image: "python:3.7"

before_script:
  - export PYTHONPATH="$PYTHONPATH:."
  - python -c "import sys;print(sys.path)"
  - pip install -r requirements.txt

stages:
  - Static Analysis
  - Test

flake8:
  stage: Static Analysis
  script:
  - flake8 --max-line-length=120 mrt_flask/*.py

pylint:
  stage: Static Analysis
  allow_failure: true
  script:
  - pylint -d C0301 mrt_flask/*.py


# TOFIX: see why they aren't working (even locally)

#mypy:
#  stage: Static Analysis
#  script:
#  - python -m mypy mrt_flask/mrt_app/file.py
#  - python -m mypy mrt_flask/mrt_app/directory.py


#pytest:
#  stage: Test
#  script:
#    - pytest

