image: "python:3.7"

before_script:
  - export PYTHONPATH="$PYTHONPATH:."
  - python -c "import sys;print(sys.path)"
  - pip install -r requirements.txt

stages:
  - Static Analysis
  - Test

flake8:
  stage: Static Analysis
  script:
  - flake8 --max-line-length=120 *.py

pylint:
  stage: Static Analysis
  allow_failure: true
  script:
  - pylint *.py


mypy:
  stage: Static Analysis
  script:
  - python -m mypy *.py


#pytest:
#  stage: Test
#  script:
#    - pytest

